import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  "https://snukdiykaemmhukbsioe.supabase.co",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNudWtkaXlrYWVtbWh1a2JzaW9lIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mjc2MTc3MiwiZXhwIjoyMDg4MzM3NzcyfQ.GwfCTEmVPZNSy2psVsbfsDB6_8Gwqsim_d4Opp5D9oU"
);

const SERVICE_CENTERS = [
  { brand:"Samsung",   name:"Samsung SmartCafé – Andheri",       address:"Shop 4, Prem Plaza, Andheri West",       area:"Andheri",     city:"Mumbai", state:"Maharashtra", pincode:"400058", phone:"1800 5 7267864", email:"support@samsung.com",   latitude:19.1313, longitude:72.8258, map_url:"https://www.google.com/maps/search/?api=1&query=Samsung+SmartCafe+Andheri+West+Mumbai",                                       warranty_label:"Samsung Warranty & Repair",       warranty_url:"https://www.samsung.com/in/support/warranty/" },
  { brand:"Samsung",   name:"Samsung Service Centre – Dadar",    address:"22, Govardhan Society, Dadar East",      area:"Dadar",       city:"Mumbai", state:"Maharashtra", pincode:"400014", phone:"1800 5 7267864", email:"support@samsung.com",   latitude:19.0178, longitude:72.8478, map_url:"https://www.google.com/maps/search/?api=1&query=Samsung+Service+Centre+Dadar+East+Mumbai",                                    warranty_label:"Samsung Warranty & Repair",       warranty_url:"https://www.samsung.com/in/support/warranty/" },
  { brand:"Apple",     name:"Apple Authorised Service – Bandra", address:"Ground Floor, Hill Road, Bandra West",   area:"Bandra",      city:"Mumbai", state:"Maharashtra", pincode:"400050", phone:"1800 2000 744",  email:"support@apple.com",     latitude:19.0544, longitude:72.8404, map_url:"https://www.google.com/maps/search/?api=1&query=Apple+Authorised+Service+Hill+Road+Bandra+West+Mumbai",                      warranty_label:"Apple Repair & Service",          warranty_url:"https://support.apple.com/en-in/repair" },
  { brand:"Apple",     name:"iCare Apple Service – Powai",       address:"Hiranandani Gardens, Powai",             area:"Powai",       city:"Mumbai", state:"Maharashtra", pincode:"400076", phone:"022-25701234",   email:"icare@example.com",     latitude:19.1176, longitude:72.9060, map_url:"https://www.google.com/maps/search/?api=1&query=Apple+Service+Centre+Hiranandani+Gardens+Powai+Mumbai",                      warranty_label:"Apple Repair & Service",          warranty_url:"https://support.apple.com/en-in/repair" },
  { brand:"LG",        name:"LG Service Centre – Borivali",      address:"Shop 7, Chandavarkar Rd, Borivali West", area:"Borivali",    city:"Mumbai", state:"Maharashtra", pincode:"400092", phone:"1800 315 9999",  email:"lgcare@lge.com",        latitude:19.2307, longitude:72.8567, map_url:"https://www.google.com/maps/search/?api=1&query=LG+Service+Centre+Chandavarkar+Road+Borivali+West+Mumbai",                   warranty_label:"LG Warranty Registration",        warranty_url:"https://www.lg.com/in/support/warranty-information" },
  { brand:"LG",        name:"LG Service Centre – Thane",         address:"Gokhale Road, Naupada, Thane West",      area:"Thane",       city:"Mumbai", state:"Maharashtra", pincode:"400602", phone:"1800 315 9999",  email:"lgcare@lge.com",        latitude:19.1972, longitude:72.9700, map_url:"https://www.google.com/maps/search/?api=1&query=LG+Service+Centre+Gokhale+Road+Naupada+Thane+West",                          warranty_label:"LG Warranty Registration",        warranty_url:"https://www.lg.com/in/support/warranty-information" },
  { brand:"Sony",      name:"Sony Service Centre – Malad",       address:"S.V. Road, Malad West",                  area:"Malad",       city:"Mumbai", state:"Maharashtra", pincode:"400064", phone:"1800 103 7799",  email:"sony.india@sony.com",   latitude:19.1864, longitude:72.8481, map_url:"https://www.google.com/maps/search/?api=1&query=Sony+Service+Centre+SV+Road+Malad+West+Mumbai",                               warranty_label:"Sony Warranty & Support",         warranty_url:"https://www.sony.co.in/en/articles/warranty" },
  { brand:"Sony",      name:"Sony Authorised – Vashi",           address:"Plot 17, Sector 17, Vashi, Navi Mumbai", area:"Vashi",       city:"Mumbai", state:"Maharashtra", pincode:"400703", phone:"1800 103 7799",  email:"sony.india@sony.com",   latitude:19.0771, longitude:73.0071, map_url:"https://www.google.com/maps/search/?api=1&query=Sony+Authorised+Service+Centre+Sector+17+Vashi+Navi+Mumbai",                 warranty_label:"Sony Warranty & Support",         warranty_url:"https://www.sony.co.in/en/articles/warranty" },
  { brand:"Whirlpool", name:"Whirlpool Service – Kandivali",     address:"Thakur Village, Kandivali East",         area:"Kandivali",   city:"Mumbai", state:"Maharashtra", pincode:"400101", phone:"1800 208 1800",  email:"whirlpool@support.com", latitude:19.2041, longitude:72.8737, map_url:"https://www.google.com/maps/search/?api=1&query=Whirlpool+Service+Centre+Thakur+Village+Kandivali+East+Mumbai",               warranty_label:"Whirlpool Warranty Extension",    warranty_url:"https://www.whirlpool.co.in/extended-warranty.html" },
  { brand:"Bosch",     name:"Bosch Home Appliance Service",      address:"Kurla-Andheri Road, Saki Naka",          area:"Saki Naka",   city:"Mumbai", state:"Maharashtra", pincode:"400072", phone:"1800 266 1880",  email:"contact@bosch.in",      latitude:19.1025, longitude:72.8851, map_url:"https://www.google.com/maps/search/?api=1&query=Bosch+Home+Appliance+Service+Centre+Saki+Naka+Mumbai",                       warranty_label:"Bosch Home Warranty & Service",   warranty_url:"https://www.bosch-home.com/in/services/warranty.html" },
  { brand:"HP",        name:"HP Service Centre – Lower Parel",   address:"Kamala Mills Compound, Lower Parel",     area:"Lower Parel", city:"Mumbai", state:"Maharashtra", pincode:"400013", phone:"1800 108 4747",  email:"hp.support@hp.com",     latitude:18.9972, longitude:72.8310, map_url:"https://www.google.com/maps/search/?api=1&query=HP+Service+Centre+Kamala+Mills+Lower+Parel+Mumbai",                           warranty_label:"HP Warranty Check & Extend",      warranty_url:"https://support.hp.com/in-en/checkwarranty" },
  { brand:"Dell",      name:"Dell Exclusive Store & Service",    address:"Phoenix Marketcity, Kurla West",         area:"Kurla",       city:"Mumbai", state:"Maharashtra", pincode:"400070", phone:"1800 425 4051",  email:"dell.support@dell.com", latitude:19.0862, longitude:72.8793, map_url:"https://www.google.com/maps/search/?api=1&query=Dell+Exclusive+Store+Service+Phoenix+Marketcity+Kurla+Mumbai",                warranty_label:"Dell Warranty Status & Renew",    warranty_url:"https://www.dell.com/en-in/lp/dt/dell-pro-support" },
  { brand:"OnePlus",   name:"OnePlus Service Centre – Andheri",  address:"Infinity Mall, Andheri West",            area:"Andheri",     city:"Mumbai", state:"Maharashtra", pincode:"400053", phone:"1800 102 8411",  email:"support@oneplus.com",   latitude:19.1362, longitude:72.8296, map_url:"https://www.google.com/maps/search/?api=1&query=OnePlus+Service+Centre+Infinity+Mall+Andheri+West+Mumbai",                    warranty_label:"OnePlus Warranty & Repair",       warranty_url:"https://www.oneplus.com/in/support/warranty" },
  { brand:"Xiaomi",    name:"Mi Service Centre – Dharavi",       address:"90 Feet Road, Dharavi",                  area:"Dharavi",     city:"Mumbai", state:"Maharashtra", pincode:"400017", phone:"1800 103 6286",  email:"support@mi.com",        latitude:19.0422, longitude:72.8553, map_url:"https://www.google.com/maps/search/?api=1&query=Mi+Xiaomi+Service+Centre+90+Feet+Road+Dharavi+Mumbai",                       warranty_label:"Xiaomi Mi Care Warranty",         warranty_url:"https://www.mi.com/in/service/warranty" },
  { brand:"Lenovo",    name:"Lenovo Authorised Service – BKC",   address:"G-Block, Bandra Kurla Complex",          area:"BKC",         city:"Mumbai", state:"Maharashtra", pincode:"400051", phone:"1800 3000 9990", email:"lenovo@support.com",    latitude:19.0596, longitude:72.8650, map_url:"https://www.google.com/maps/search/?api=1&query=Lenovo+Authorised+Service+Centre+Bandra+Kurla+Complex+Mumbai",                warranty_label:"Lenovo Warranty Lookup & Extend", warranty_url:"https://pcsupport.lenovo.com/in/en/warrantylookup" },
];

console.log("Seeding service centers…");
const { data: existing } = await supabase.from("service_centers").select("name");
const existingNames = new Set((existing ?? []).map((r) => r.name));
const toInsert = SERVICE_CENTERS.filter((c) => !existingNames.has(c.name));

if (toInsert.length === 0) {
  console.log("All service centers already present — nothing to insert.");
  process.exit(0);
}

const { data, error } = await supabase.from("service_centers").insert(toInsert).select("brand, name");
if (error) {
  console.error("Insert failed:", error.message, error.details);
  process.exit(1);
}

data.forEach((r) => console.log(`  ✓ ${r.brand} — ${r.name}`));
console.log(`\nDone: ${data.length} service centers inserted.`);
